FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .

RUN apt-get update && apt-get install -y unixodbc
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host packagemanger.posit.co --no-cache-dir -r requirements.txt 

COPY orchestrator/ ./orchestrator/
COPY loader/ ./loader/

CMD ["python", "orchestrator/main.py"]
