FROM python:3.11-slim

WORKDIR /app/orchestrator
COPY requirements.txt .

# Install prerequisites for mssql-python
RUN apt-get update && apt-get install -y --no-install-recommends \
    libltdl7 \
    libkrb5-3 \
    libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host packagemanger.posit.co --no-cache-dir -r requirements.txt

COPY orchestrator/ ./
COPY loader/ ../loader/

CMD ["python", "main.py"]
